export const TOGGLE_FAVORITE_REQUEST = 'TOGGLE_FAVORITE_REQUEST';
export const TOGGLE_FAVORITE_SUCCESS = 'TOGGLE_FAVORITE_SUCCESS';
export const TOGGLE_FAVORITE_FAIL = 'TOGGLE_FAVORITE_FAIL';

export const GET_FAVORITES_REQUEST = 'GET_FAVORITES_REQUEST';
export const GET_FAVORITES_SUCCESS = 'GET_FAVORITES_SUCCESS';
export const GET_FAVORITES_FAIL = 'GET_FAVORITES_FAIL';

export const CHECK_FAVORITE_REQUEST = 'CHECK_FAVORITE_REQUEST';
export const CHECK_FAVORITE_SUCCESS = 'CHECK_FAVORITE_SUCCESS';
export const CHECK_FAVORITE_FAIL = 'CHECK_FAVORITE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';