export const PROCESS_PAYMENT_REQUEST = 'PROCESS_PAYMENT_REQUEST';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAIL = 'PROCESS_PAYMENT_FAIL';

export const GET_ORDER_TOTAL_REQUEST = 'GET_ORDER_TOTAL_REQUEST';
export const GET_ORDER_TOTAL_SUCCESS = 'GET_ORDER_TOTAL_SUCCESS';
export const GET_ORDER_TOTAL_FAIL = 'GET_ORDER_TOTAL_FAIL';

export const GET_STRIPE_KEY_REQUEST = 'GET_STRIPE_KEY_REQUEST';
export const GET_STRIPE_KEY_SUCCESS = 'GET_STRIPE_KEY_SUCCESS';
export const GET_STRIPE_KEY_FAIL = 'GET_STRIPE_KEY_FAIL';

export const CLEAR_PAYMENT_ERRORS = 'CLEAR_PAYMENT_ERRORS';
export const RESET_PAYMENT_STATE = 'RESET_PAYMENT_STATE';